name: emmabirnbaum
favicon: null
layout_spectrum: 0.3696401407942176
typography_spectrum: 0.5994947317522019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8577989279292524
  lightness: 0.08411035686731339
  saturation: 0.6752062579616904
  rhythmicContrast: 0.9046663420740515
purpose: []
