name: emmabirnbaum
favicon: null
layout_spectrum: 0.34151
typography_spectrum: 0.5994947317522019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bdc9d5'
    - '#845849'
    - '#b27d6d'
    - '#48495c'
    - '#070a13'
  brandStrength: 0.8577989279292524
  lightness: 0
  saturation: 0.6752062579616904
  rhythmicContrast: 0.9046663420740515
purpose: []
